/* Bang gia dich vu Nha Khoa Hoang Bach - lay tu hai file PDF phong kham gui.
   n = ten dich vu, g = nhom, p = don gia (0 = bao gia theo ca), d = don vi,
   bh = bao hanh, x = xuat xu, c = ghi chu. */
'use strict';
const BANG_GIA = [
  /* ---- Kham va chan doan hinh anh ---- */
  {g:'Chẩn đoán hình ảnh', n:'Khám và tư vấn',                        p:0, mp:1,  d:'lần',  c:'Miễn phí (giá trị 200.000đ)'},
  {g:'Chẩn đoán hình ảnh', n:'Phim quanh chóp',                       p:50000,    d:'phim'},
  {g:'Chẩn đoán hình ảnh', n:'Phim răng toàn cảnh (Panorex)',         p:150000,   d:'phim'},
  {g:'Chẩn đoán hình ảnh', n:'Phim sọ nghiêng (Cephalo)',             p:350000,   d:'phim'},
  {g:'Chẩn đoán hình ảnh', n:'Phim Conebeam CT',                      p:650000,   d:'phim'},

  /* ---- Nha chu ---- */
  {g:'Nha chu', n:'Cạo vôi răng — mức độ 1',                          p:200000,   d:'2 hàm'},
  {g:'Nha chu', n:'Cạo vôi răng — mức độ 2',                          p:300000,   d:'2 hàm'},
  {g:'Nha chu', n:'Cạo vôi răng — mức độ 3',                          p:400000,   d:'2 hàm'},
  {g:'Nha chu', n:'Cạo vôi răng — mức độ 4',                          p:500000,   d:'2 hàm'},
  {g:'Nha chu', n:'Thổi muối khoáng (Air Polishing) — mức độ 1',      p:600000,   d:'2 hàm'},
  {g:'Nha chu', n:'Thổi muối khoáng (Air Polishing) — mức độ 2',      p:800000,   d:'2 hàm'},
  {g:'Nha chu', n:'Thổi muối khoáng (Air Polishing) — mức độ 3',      p:1000000,  d:'2 hàm'},
  {g:'Nha chu', n:'Nạo túi nha chu',                                  p:500000,   d:'răng'},

  /* ---- Tram rang ---- */
  {g:'Trám răng', n:'Trám sâu răng phía trong — tiêu chuẩn',          p:200000,   d:'răng'},
  {g:'Trám răng', n:'Trám sâu răng phía trong — nâng cao',            p:300000,   d:'răng'},
  {g:'Trám răng', n:'Trám sâu răng phía trong — cao cấp',             p:400000,   d:'răng'},
  {g:'Trám răng', n:'Trám răng cửa — tiêu chuẩn',                     p:500000,   d:'răng'},
  {g:'Trám răng', n:'Trám răng cửa — nâng cao',                       p:600000,   d:'răng'},
  {g:'Trám răng', n:'Trám răng cửa — cao cấp',                        p:700000,   d:'răng'},
  {g:'Trám răng', n:'Trám răng cửa — premium',                        p:800000,   d:'răng'},
  {g:'Trám răng', n:'Đóng khe thưa Bioclear — mức độ 1',              p:1000000,  d:'răng'},
  {g:'Trám răng', n:'Đóng khe thưa Bioclear — mức độ 2',              p:1500000,  d:'răng'},
  {g:'Trám răng', n:'Đắp răng khểnh — mức độ 1',                      p:1500000,  d:'răng'},
  {g:'Trám răng', n:'Đắp răng khểnh — mức độ 2',                      p:1800000,  d:'răng'},
  {g:'Trám răng', n:'Đắp răng khểnh — mức độ 3',                      p:2000000,  d:'răng'},
  {g:'Trám răng', n:'Đắp răng khểnh — mức độ 4',                      p:2500000,  d:'răng'},

  /* ---- Tham my ---- */
  {g:'Thẩm mỹ', n:'Tẩy trắng tại ghế — thường (hơi ê)',               p:2000000,  d:'2 hàm'},
  {g:'Thẩm mỹ', n:'Tẩy trắng tại ghế — tốt (không ê)',                p:3000000,  d:'2 hàm'},
  {g:'Thẩm mỹ', n:'Tẩy trắng về nhà — 2 máng tẩy + 1 ống thuốc',      p:700000,   d:'2 hàm'},
  {g:'Thẩm mỹ', n:'Tẩy trắng về nhà — 2 máng tẩy',                    p:400000,   d:'bộ'},
  {g:'Thẩm mỹ', n:'Tẩy trắng về nhà — 1 máng tẩy',                    p:300000,   d:'cái'},
  {g:'Thẩm mỹ', n:'Thuốc tẩy trắng về nhà',                           p:300000,   d:'ống'},
  {g:'Thẩm mỹ', n:'Gắn hột xoàn — hột của phòng nha',                 p:500000,   d:'răng'},
  {g:'Thẩm mỹ', n:'Gắn hột xoàn — hột của khách',                     p:300000,   d:'răng'},

  /* ---- Rang tre em ---- */
  {g:'Răng trẻ em', n:'Vệ sinh răng trẻ em',                          p:100000,   d:'2 hàm'},
  {g:'Răng trẻ em', n:'Phủ vecni fluor',                              p:300000,   d:'2 hàm'},
  {g:'Răng trẻ em', n:'Trám răng sữa (GIC)',                          p:200000,   d:'răng'},
  {g:'Răng trẻ em', n:'Điều trị tủy + trám răng sữa',                 p:700000,   d:'răng'},
  {g:'Răng trẻ em', n:'Bọc mão kim loại răng sữa',                    p:500000,   d:'răng'},
  {g:'Răng trẻ em', n:'Gói chăm sóc Robot (1 năm)',                   p:1000000,  d:'gói',  c:'Giá gốc 1.750.000đ — tiết kiệm 750.000đ'},
  {g:'Răng trẻ em', n:'Gói chăm sóc Siêu Nhân (1 năm)',               p:2000000,  d:'gói',  c:'Giá gốc 4.100.000đ — tiết kiệm 2.100.000đ'},
  {g:'Răng trẻ em', n:'Gói chăm sóc Super Man (1 năm)',               p:3000000,  d:'gói',  c:'Giá gốc 6.000.000đ — tiết kiệm 3.000.000đ'},

  /* ---- Nho rang ---- */
  {g:'Nhổ răng', n:'Nhổ răng sữa — tê bôi',                           p:50000,    d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng sữa — tê tiêm',                          p:100000,   d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng vĩnh viễn — 1 chân',                     p:300000,   d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng vĩnh viễn — 2 chân',                     p:500000,   d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng vĩnh viễn — 3 chân',                     p:800000,   d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng khôn mọc thẳng — mức độ 1',              p:800000,   d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng khôn mọc thẳng — mức độ 2',              p:1000000,  d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng khôn mọc thẳng — mức độ 3',              p:1200000,  d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng khôn mọc lệch — mức độ 1',               p:1500000,  d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng khôn mọc lệch — mức độ 2',               p:2000000,  d:'răng'},
  {g:'Nhổ răng', n:'Nhổ răng khôn mọc lệch — mức độ 3',               p:3000000,  d:'răng'},
  {g:'Nhổ răng', n:'Khâu sau nhổ răng',                               p:100000,   d:'răng'},
  {g:'Nhổ răng', n:'Màng giàu tiểu cầu PRF',                          p:500000,   d:'màng'},

  /* ---- Dieu tri tuy ---- */
  {g:'Điều trị tủy', n:'Nội nha răng cửa — gói cơ bản',               p:1300000,  d:'răng', c:'Đã bao gồm trám, răng sứ tính riêng'},
  {g:'Điều trị tủy', n:'Nội nha răng cửa — gói cao cấp',              p:1800000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng cửa — gói VIP',                  p:3000000,  d:'răng', c:'Kính hiển vi'},
  {g:'Điều trị tủy', n:'Nội nha răng cối nhỏ — gói cơ bản',           p:1500000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng cối nhỏ — gói cao cấp',          p:2000000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng cối nhỏ — gói VIP',              p:3500000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng cối lớn — gói cơ bản',           p:1700000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng cối lớn — gói cao cấp',          p:2200000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng cối lớn — gói VIP',              p:4000000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng khôn — gói cơ bản',              p:3000000,  d:'răng'},
  {g:'Điều trị tủy', n:'Nội nha răng khôn — gói cao cấp',             p:5000000,  d:'răng'},
  {g:'Điều trị tủy', n:'Điều trị tủy lại',                            p:1000000,  d:'răng', c:'Cộng thêm vào giá gói'},
  {g:'Điều trị tủy', n:'Răng nhiễm trùng nhiều / trường hợp đặc biệt', p:1000000, d:'răng', c:'Cộng thêm vào giá gói'},

  /* ---- Phuc hinh su co dinh ---- */
  {g:'Phục hình sứ', n:'Răng toàn sứ Zirconia',                       p:3000000,  d:'răng', x:'Hàn Quốc', bh:'10 năm'},
  {g:'Phục hình sứ', n:'Răng toàn sứ DDBio',                          p:4000000,  d:'răng', x:'Đức',      bh:'10 năm'},
  {g:'Phục hình sứ', n:'Răng toàn sứ Cercon',                         p:5000000,  d:'răng', x:'Đức',      bh:'10 năm'},
  {g:'Phục hình sứ', n:'Răng toàn sứ Lava',                           p:6000000,  d:'răng', x:'Mỹ',       bh:'15 năm'},
  {g:'Phục hình sứ', n:'Răng toàn sứ Orodent',                        p:10000000, d:'răng', x:'Ý',        bh:'19 năm'},
  {g:'Phục hình sứ', n:'Răng sứ kim loại thường',                     p:1000000,  d:'răng', x:'Mỹ',       bh:'3 năm'},
  {g:'Phục hình sứ', n:'Răng sứ Chrome - Coban',                      p:2000000,  d:'răng', x:'Đức',      bh:'5 năm'},
  {g:'Phục hình sứ', n:'Răng sứ Titan',                               p:2500000,  d:'răng', x:'Mỹ',       bh:'7 năm'},
  {g:'Phục hình sứ', n:'Mặt dán sứ Veneer Emax Press',                p:8000000,  d:'răng', x:'Đức',      bh:'10 năm'},
  {g:'Phục hình sứ', n:'Mặt dán sứ Veneer Lisi Press',                p:6000000,  d:'răng', x:'Nhật',     bh:'10 năm'},
  {g:'Phục hình sứ', n:'Endocrown',                                   p:5000000,  d:'răng', x:'Đức',      bh:'10 năm'},
  {g:'Phục hình sứ', n:'Inlay / Onlay Emax',                          p:5000000,  d:'răng', x:'Đức',      bh:'10 năm'},
  {g:'Phục hình sứ', n:'Cùi giả Zirconia',                            p:1000000,  d:'răng'},
  {g:'Phục hình sứ', n:'Cùi giả kim loại',                            p:300000,   d:'răng'},
  {g:'Phục hình sứ', n:'Gắn lại răng toàn sứ',                        p:300000,   d:'răng'},
  {g:'Phục hình sứ', n:'Gắn lại răng sứ kim loại',                    p:200000,   d:'răng'},

  /* ---- Phuc hinh thao lap ---- */
  {g:'Phục hình tháo lắp', n:'Răng tháo lắp nhựa — Nhật',             p:1000000,  d:'răng'},
  {g:'Phục hình tháo lắp', n:'Răng tháo lắp nhựa — Mỹ',               p:500000,   d:'răng'},
  {g:'Phục hình tháo lắp', n:'Răng tháo lắp nhựa — Đức',              p:300000,   d:'răng'},
  {g:'Phục hình tháo lắp', n:'Hàm khung hợp kim thường',              p:3000000,  d:'cái'},
  {g:'Phục hình tháo lắp', n:'Hàm khung hợp kim Titan',               p:4000000,  d:'cái'},
  {g:'Phục hình tháo lắp', n:'Lưới',                                  p:500000,   d:'cái'},
  {g:'Phục hình tháo lắp', n:'Móc dẻo',                               p:1500000,  d:'cái'},
  {g:'Phục hình tháo lắp', n:'Nhựa cường lực',                        p:500000,   d:'cái'},
  {g:'Phục hình tháo lắp', n:'Mắc cài bi',                            p:2000000,  d:'cái'},
  {g:'Phục hình tháo lắp', n:'Chốt bi Rhein83',                       p:3000000,  d:'cái'},
  {g:'Phục hình tháo lắp', n:'Ron',                                   p:500000,   d:'cái'},
  {g:'Phục hình tháo lắp', n:'Vá hàm nứt, vỡ',                        p:500000,   d:'cái'},
  {g:'Phục hình tháo lắp', n:'Đệm hàm',                               p:500000,   d:'cái'},
  {g:'Phục hình tháo lắp', n:'Thêm móc',                              p:500000,   d:'cái'},

  /* ---- Chinh nha ---- */
  {g:'Chỉnh nha', n:'Chỉnh nha sớm',                                  p:10000000, d:'ca', c:'10 – 15 triệu tùy ca'},
  {g:'Chỉnh nha', n:'Chỉnh nha mắc cài kim loại',                     p:30000000, d:'ca', c:'30 – 45 triệu tùy ca'},
  {g:'Chỉnh nha', n:'Chỉnh nha mắc cài sứ',                           p:30000000, d:'ca', c:'30 – 50 triệu tùy ca'},
  {g:'Chỉnh nha', n:'Chỉnh nha khay trong suốt',                      p:60000000, d:'ca', c:'60 – 110 triệu tùy ca'},

  /* ---- Implant ---- */
  {g:'Implant', n:'Trụ Implant Hàn Quốc',                             p:15000000, d:'răng', bh:'5 năm'},
  {g:'Implant', n:'Trụ Implant Pháp',                                 p:20000000, d:'răng', bh:'8 năm'},
  {g:'Implant', n:'Trụ Implant Mỹ',                                   p:25000000, d:'răng', bh:'10 năm'},
  {g:'Implant', n:'Trụ Implant Thụy Sĩ',                              p:30000000, d:'răng', bh:'15 năm'},
  {g:'Implant', n:'Hàm tạm trên Implant',                             p:10000000, d:'hàm'},
  {g:'Implant', n:'Hàm nhựa trên Implant',                            p:15000000, d:'hàm'},
  {g:'Implant', n:'Thanh bar liên kết',                               p:30000000, d:'thanh'},
  {g:'Implant', n:'Ghép xương — bột xương Hàn Quốc',                  p:5000000,  d:'lọ'},
  {g:'Implant', n:'Ghép xương — bột xương Đức',                       p:8000000,  d:'lọ'},
  {g:'Implant', n:'Màng xương Collagen',                              p:5000000,  d:'lọ'},
  {g:'Implant', n:'Nâng xoang kín',                                   p:4000000,  d:'xoang'},
  {g:'Implant', n:'Nâng xoang hở + ghép xương',                       p:10000000, d:'xoang'},
  {g:'Implant', n:'All on 4 hàm plastic — Hàn Quốc',                  p:121000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ kim loại — Hàn Quốc',                  p:142000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ Zirconia — Hàn Quốc',                  p:166000000, d:'hàm'},
  {g:'Implant', n:'All on 6 hàm plastic — Hàn Quốc',                  p:154000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ kim loại — Hàn Quốc',                  p:181000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ Zirconia — Hàn Quốc',                  p:224000000, d:'hàm'},
  {g:'Implant', n:'All on 4 hàm plastic — Pháp',                      p:141000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ kim loại — Pháp',                      p:162000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ Zirconia — Pháp',                      p:186000000, d:'hàm'},
  {g:'Implant', n:'All on 6 hàm plastic — Pháp',                      p:184000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ kim loại — Pháp',                      p:211000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ Zirconia — Pháp',                      p:254000000, d:'hàm'},
  {g:'Implant', n:'All on 4 hàm plastic — Mỹ',                        p:161000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ kim loại — Mỹ',                        p:182000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ Zirconia — Mỹ',                        p:206000000, d:'hàm'},
  {g:'Implant', n:'All on 6 hàm plastic — Mỹ',                        p:214000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ kim loại — Mỹ',                        p:241000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ Zirconia — Mỹ',                        p:284000000, d:'hàm'},
  {g:'Implant', n:'All on 4 hàm plastic — Thụy Sĩ',                   p:181000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ kim loại — Thụy Sĩ',                   p:202000000, d:'hàm'},
  {g:'Implant', n:'All on 4 sứ Zirconia — Thụy Sĩ',                   p:226000000, d:'hàm'},
  {g:'Implant', n:'All on 6 hàm plastic — Thụy Sĩ',                   p:244000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ kim loại — Thụy Sĩ',                   p:271000000, d:'hàm'},
  {g:'Implant', n:'All on 6 sứ Zirconia — Thụy Sĩ',                   p:314000000, d:'hàm'},

  /* ---- Khac ---- */
  {g:'Khác', n:'Nẹp cố định răng chấn thương',                        p:1000000,  d:'răng'},
  {g:'Khác', n:'Đặt chốt',                                            p:300000,   d:'chốt'},
];
